name: Publish Python Package to PyPI

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch (adjust as necessary)

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the base image

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine  # Install necessary packaging tools

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel  # Build the distribution files

      - name: Upload package to PyPI
        run: |
          twine upload dist/*  # Upload the distribution files to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
